"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var content_types_1 = require("./content-types");
Object.defineProperty(exports, "contentTypesXML", { enumerable: true, get: function () { return content_types_1.default; } });
var core_1 = require("./core");
Object.defineProperty(exports, "generateCoreXML", { enumerable: true, get: function () { return core_1.default; } });
var document_rels_1 = require("./document-rels");
Object.defineProperty(exports, "documentRelsXML", { enumerable: true, get: function () { return document_rels_1.default; } });
var rels_1 = require("./rels");
Object.defineProperty(exports, "relsXML", { enumerable: true, get: function () { return rels_1.default; } });
var numbering_1 = require("./numbering");
Object.defineProperty(exports, "generateNumberingXMLTemplate", { enumerable: true, get: function () { return numbering_1.default; } });
var styles_1 = require("./styles");
Object.defineProperty(exports, "generateStylesXML", { enumerable: true, get: function () { return styles_1.default; } });
var font_table_1 = require("./font-table");
Object.defineProperty(exports, "fontTableXML", { enumerable: true, get: function () { return font_table_1.default; } });
var settings_1 = require("./settings");
Object.defineProperty(exports, "settingsXML", { enumerable: true, get: function () { return settings_1.default; } });
var web_settings_1 = require("./web-settings");
Object.defineProperty(exports, "webSettingsXML", { enumerable: true, get: function () { return web_settings_1.default; } });
var generic_rels_1 = require("./generic-rels");
Object.defineProperty(exports, "genericRelsXML", { enumerable: true, get: function () { return generic_rels_1.default; } });
//# sourceMappingURL=index.js.map