"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.unicodeIcons = void 0;
exports.unicodeIcons = [
    { symbol: "�", unicodeHex: "FFFD", code: 65533, alias: "unknown", name: "unknown", tags: ["color_unknown"], nameUnicode: "REPLACEMENT CHARACTER", width: "+0.5ex" },
    { symbol: "×", unicodeHex: "D7", code: 215, alias: "times", name: "multiplication_sign", tags: ["color_times"], nameUnicode: "MULTIPLICATION SIGN", width: "+0.5ex" },
    { symbol: "•", unicodeHex: "2022", code: 8226, alias: "", name: "bullet", tags: ["color_bullet"], nameUnicode: "BULLET", width: "+0.5ex" },
    { symbol: "※", unicodeHex: "203B", code: 8251, alias: "", name: "reference_mark", tags: ["color_reference_mark"], nameUnicode: "REFERENCE MARK", width: "+0.5ex" },
    { symbol: "←", unicodeHex: "2190", code: 8592, alias: "left_arrow", name: "leftwards_arrow", tags: ["color_left_arrow"], nameUnicode: "LEFTWARDS ARROW", width: "+0.5ex" },
    { symbol: "↑", unicodeHex: "2191", code: 8593, alias: "up_arrow", name: "upwards_arrow", tags: ["color_up_arrow"], nameUnicode: "UPWARDS ARROW", width: "+0.5ex" },
    { symbol: "→", unicodeHex: "2192", code: 8594, alias: "right_arrow", name: "rightwards_arrow", tags: ["color_right_arrow"], nameUnicode: "RIGHTWARDS ARROW", width: "+0.5ex" },
    { symbol: "↓", unicodeHex: "2193", code: 8595, alias: "down_arrow", name: "downwards_arrow", tags: ["color_down_arrow"], nameUnicode: "DOWNWARDS ARROW", width: "+0.5ex" },
    { symbol: "①", unicodeHex: "2460", code: 9312, alias: "circled_one", name: "circled_digit_one", tags: ["color_circled_one"], nameUnicode: "CIRCLED DIGIT ONE", width: "+0.6ex" },
    { symbol: "②", unicodeHex: "2461", code: 9313, alias: "circled_two", name: "circled_digit_two", tags: ["color_circled_two"], nameUnicode: "CIRCLED DIGIT TWO", width: "+0.6ex" },
    { symbol: "③", unicodeHex: "2462", code: 9314, alias: "circled_three", name: "circled_digit_three", tags: ["color_circled_three"], nameUnicode: "CIRCLED DIGIT THREE", width: "+0.6ex" },
    { symbol: "④", unicodeHex: "2463", code: 9315, alias: "circled_four", name: "circled_digit_four", tags: ["color_circled_four"], nameUnicode: "CIRCLED DIGIT FOUR", width: "+0.6ex" },
    { symbol: "⑤", unicodeHex: "2464", code: 9316, alias: "circled_five", name: "circled_digit_five", tags: ["color_circled_five"], nameUnicode: "CIRCLED DIGIT FIVE", width: "+0.6ex" },
    { symbol: "⑥", unicodeHex: "2465", code: 9317, alias: "circled_six", name: "circled_digit_six", tags: ["color_circled_six"], nameUnicode: "CIRCLED DIGIT SIX", width: "+0.6ex" },
    { symbol: "⑦", unicodeHex: "2466", code: 9318, alias: "circled_seven", name: "circled_digit_seven", tags: ["color_circled_seven"], nameUnicode: "CIRCLED DIGIT SEVEN", width: "+0.6ex" },
    { symbol: "⑧", unicodeHex: "2467", code: 9319, alias: "circled_eight", name: "circled_digit_eight", tags: ["color_circled_eight"], nameUnicode: "CIRCLED DIGIT EIGHT", width: "+0.6ex" },
    { symbol: "⑨", unicodeHex: "2468", code: 9320, alias: "circled_nine", name: "circled_digit_nine", tags: ["color_circled_nine"], nameUnicode: "CIRCLED DIGIT NINE", width: "+0.6ex" },
    { symbol: "⓪", unicodeHex: "24EA", code: 9450, alias: "circled_zero", name: "circled_digit_zero", tags: ["color_circled_zero"], nameUnicode: "CIRCLED DIGIT ZERO", width: "+0.6ex" },
    { symbol: "■", unicodeHex: "25A0", code: 9632, alias: "", name: "black_square", tags: ["color_square"], nameUnicode: "BLACK SQUARE", width: "+0.5ex" },
    { symbol: "▲", unicodeHex: "25B2", code: 9650, alias: "black_triangle", name: "black_up_pointing_triangle", tags: ["color_triangle"], nameUnicode: "BLACK UP-POINTING TRIANGLE", width: "+0.5ex" },
    { symbol: "▼", unicodeHex: "25BC", code: 9660, alias: "black_triangle_down", name: "black_down_pointing_triangle", tags: ["color_triangle_down"], nameUnicode: "BLACK DOWN-POINTING TRIANGLE", width: "+0.5ex" },
    { symbol: "▶", unicodeHex: "25B6", code: 9654, alias: "black_triangle_right", name: "black_right_pointing_triangle", tags: ["color_triangle_right"], nameUnicode: "BLACK RIGHT-POINTING TRIANGLE", width: "+0.5ex" },
    { symbol: "◀", unicodeHex: "25C0", code: 9664, alias: "black_triangle_left", name: "black_left_pointing_triangle", tags: ["color_triangle_left"], nameUnicode: "BLACK LEFT-POINTING TRIANGLE", width: "+0.5ex" },
    { symbol: "△", unicodeHex: "25B3", code: 9651, alias: "triangle", name: "white_up_pointing_triangle", tags: [], nameUnicode: "WHITE UP-POINTING TRIANGLE", width: "+0.5ex" },
    { symbol: "▽", unicodeHex: "25BD", code: 9661, alias: "triangle_down", name: "white_down_pointing_triangle", tags: [], nameUnicode: "WHITE DOWN-POINTING TRIANGLE", width: "+0.5ex" },
    { symbol: "▷", unicodeHex: "25B7", code: 9655, alias: "triangle_right", name: "white_right_pointing_triangle", tags: [], nameUnicode: "WHITE RIGHT-POINTING TRIANGLE", width: "+0.5ex" },
    { symbol: "◁", unicodeHex: "25C1", code: 9665, alias: "triangle_left", name: "white_left_pointing_triangle", tags: [], nameUnicode: "WHITE LEFT-POINTING TRIANGLE", width: "+0.5ex" },
    { symbol: "○", unicodeHex: "25CB", code: 9675, alias: "circle", name: "white_circle", nameUnicode: "WHITE CIRCLE", tags: [], width: "+0.5ex" },
    { symbol: "●", unicodeHex: "25CF", code: 9679, alias: "", name: "black_circle", tags: ["color_circle"], nameUnicode: "BLACK CIRCLE", width: "+0.5ex" },
    { symbol: "◎", unicodeHex: "25CE", code: 9678, alias: "", name: "bullseye", tags: ["color_bullseye"], nameUnicode: "BULLSEYE", width: "+0.5ex" },
    { symbol: "★", unicodeHex: "2605", code: 9733, alias: "", name: "black_star", tags: ["color_star"], nameUnicode: "BLACK STAR", width: "+0.5ex" },
    { symbol: "☆", unicodeHex: "2606", code: 9734, alias: "star", name: "white_star", tags: [], nameUnicode: "WHITE STAR", width: "+0.5ex" },
    { symbol: "☹", unicodeHex: "2639", code: 9785, alias: "sad_face", name: "white_frowning_face", tags: ["color_sad_face"], nameUnicode: "WHITE FROWNING FACE", width: "+0.5ex" },
    { symbol: "☺", unicodeHex: "263A", code: 9786, alias: "smiley", name: "white_smiling_face", tags: [], nameUnicode: "WHITE SMILING FACE", width: "+0.5ex" },
    { symbol: "☻", unicodeHex: "263B", code: 9787, alias: "black_smiley", name: "black_smiling_face", tags: ["color_smiley"], nameUnicode: "BLACK SMILING FACE", width: "+0.5ex" },
    { symbol: "♡", unicodeHex: "2661", code: 9825, alias: "heart", name: "white_heart_suit", tags: [], nameUnicode: "WHITE HEART SUIT", width: "+0.5ex" },
    { symbol: "♥", unicodeHex: "2665", code: 9829, alias: "black_heart", name: "black_heart_suit", tags: ["color_heart"], nameUnicode: "BLACK HEART SUIT", width: "+0.5ex" },
    { symbol: "♨", unicodeHex: "2668", code: 9832, alias: "", name: "hot_springs", tags: ["color_hot_springs"], nameUnicode: "HOT SPRINGS", width: "+0.6ex" },
    { symbol: "⦾", unicodeHex: "29BE", code: 10686, alias: "", name: "circled_white_bullet", tags: ["color_circled_white_bullet"], nameUnicode: "CIRCLED WHITE BULLET", width: "+0.5ex" },
    { symbol: "⦿", unicodeHex: "29BF", code: 10687, alias: "", name: "circled_bullet", tags: ["color_circled_bullet"], nameUnicode: "CIRCLED BULLET", width: "+0.5ex" },
    { symbol: "〈", unicodeHex: "3008", code: 12296, alias: "left_angle", name: "left_angle_bracket", tags: ["color_left_angle"], nameUnicode: "LEFT ANGLE BRACKET", width: "+0.5ex" },
    { symbol: "〉", unicodeHex: "3009", code: 12297, alias: "right_angle", name: "right_angle_bracket", tags: ["color_right_angle"], nameUnicode: "RIGHT ANGLE BRACKET", width: "+0.5ex" },
    { symbol: "・", unicodeHex: "30FB", code: 12539, alias: "middle_dot", name: "katakana_middle_dot", tags: ["color_middle_dot"], nameUnicode: "KATAKANA MIDDLE DOT", width: "+0.5ex" },
    { symbol: "☀", unicodeHex: "2600", code: 9728, alias: "black_sun", name: "black_sun_with_rays", tags: ["color_sun"], nameUnicode: "BLACK SUN WITH RAYS", width: "+0.5ex" },
    { symbol: "☼", unicodeHex: "263C", code: 9788, alias: "sun", name: "white_sun_with_rays", tags: [], nameUnicode: "WHITE SUN WITH RAYS", width: "+0.5ex" },
    { symbol: "☁", unicodeHex: "2601", code: 9729, alias: "", name: "cloud", tags: ["color_cloud"], nameUnicode: "CLOUD", width: "+0.5ex" },
    { symbol: "☂", unicodeHex: "2602", code: 9730, alias: "", name: "umbrella", tags: ["color_umbrella"], nameUnicode: "UMBRELLA", width: "+0.5ex" },
    { symbol: "☃", unicodeHex: "2603", code: 9731, alias: "", name: "snowman", tags: [], nameUnicode: "SNOWMAN", width: "+0.5ex" },
    { symbol: "☉", unicodeHex: "2609", code: 9737, alias: "astro_sun", name: "sun", tags: ["color_astro_sun"], nameUnicode: "SUN", width: "+0.5ex" },
    { symbol: "☽", unicodeHex: "263D", code: 9789, alias: "right_moon", name: "first_quarter_moon", tags: ["color_right_moon"], nameUnicode: "FIRST QUARTER MOON", width: "+0.5ex" },
    { symbol: "☾", unicodeHex: "263E", code: 9790, alias: "left_moon", name: "last_quarter_moon", tags: ["color_left_moon"], nameUnicode: "LAST QUARTER MOON", width: "+0.5ex" },
    { symbol: "☎", unicodeHex: "260E", code: 9742, alias: "", name: "black_telephone", tags: ["color_telephone"], nameUnicode: "BLACK TELEPHONE", width: "+0.6ex" },
    { symbol: "☏", unicodeHex: "260F", code: 9743, alias: "telephone", name: "white_telephone", tags: [], nameUnicode: "WHITE TELEPHONE", width: "+0.6ex" },
    { symbol: "☖", unicodeHex: "2616", code: 9750, alias: "shogi", name: "white_shogi_piece", tags: [], nameUnicode: "WHITE SHOGI PIECE", width: "+0.5ex" },
    { symbol: "☗", unicodeHex: "2617", code: 9751, alias: "black_shogi", name: "black_shogi_piece", tags: ["color_shogi"], nameUnicode: "BLACK SHOGI PIECE", width: "+0.5ex" },
    { symbol: "☘", unicodeHex: "2618", code: 9752, alias: "", name: "shamrock", tags: ["color_shamrock"], nameUnicode: "SHAMROCK", width: "+0.5ex" },
    { symbol: "☚", unicodeHex: "261A", code: 9754, alias: "black_point_left", name: "black_left_pointing_index", tags: ["color_point_left"], nameUnicode: "BLACK LEFT POINTING INDEX", width: "+0.5ex" },
    { symbol: "☜", unicodeHex: "261C", code: 9756, alias: "point_left", name: "white_left_pointing_index", tags: [], nameUnicode: "WHITE LEFT POINTING INDEX", width: "+0.5ex" },
    { symbol: "☛", unicodeHex: "261B", code: 9755, alias: "black_point_right", name: "black_right_pointing_index", tags: ["color_point_right"], nameUnicode: "BLACK RIGHT POINTING INDEX", width: "+0.5ex" },
    { symbol: "☞", unicodeHex: "261E", code: 9758, alias: "point_right", name: "white_right_pointing_index", tags: [], nameUnicode: "WHITE RIGHT POINTING INDEX", width: "+0.5ex" },
    { symbol: "☝", unicodeHex: "261D", code: 9757, alias: "point_up", name: "white_up_pointing_index", tags: ["color_point_up"], nameUnicode: "WHITE UP POINTING INDEX", width: "+0.5ex" },
    { symbol: "☟", unicodeHex: "261F", code: 9759, alias: "point_down", name: "white_down_pointing_index", tags: ["color_point_down"], nameUnicode: "WHITE DOWN POINTING INDEX", width: "+0.5ex" },
    { symbol: "☠", unicodeHex: "2620", code: 9760, alias: "skull", name: "skull_and_crossbones", tags: ["color_skull"], nameUnicode: "SKULL AND CROSSBONES", width: "+0.5ex" },
    { symbol: "☡", unicodeHex: "2621", code: 9761, alias: "caution", name: "caution_sign", tags: ["color_caution"], nameUnicode: "CAUTION SIGN", width: "+0.5ex" },
    { symbol: "☢", unicodeHex: "2622", code: 9762, alias: "radiation", name: "radioactive_sign", tags: ["color_radiation"], nameUnicode: "RADIOACTIVE SIGN", width: "+0.5ex" },
    { symbol: "☣", unicodeHex: "2623", code: 9763, alias: "biohazard", name: "biohazard_sign", tags: ["color_biohazard"], nameUnicode: "BIOHAZARD SIGN", width: "+0.5ex" },
    { symbol: "☯", unicodeHex: "262F", code: 9775, alias: "", name: "yin_yang", tags: ["color_yin_yang"], nameUnicode: "YIN YANG", width: "+0.5ex" },
    { symbol: "♀", unicodeHex: "2640", code: 9792, alias: "female", name: "female_sign", tags: ["color_female"], nameUnicode: "FEMALE SIGN", width: "+0.5ex" },
    { symbol: "♂", unicodeHex: "2642", code: 9794, alias: "male", name: "male_sign", tags: ["color_male"], nameUnicode: "MALE SIGN", width: "+0.5ex" },
    { symbol: "⚢", unicodeHex: "26A2", code: 9890, alias: "female_female", name: "doubled_female_sign", tags: ["color_female_female"], nameUnicode: "DOUBLED FEMALE SIGN", width: "+0.5ex" },
    { symbol: "⚣", unicodeHex: "26A3", code: 9891, alias: "male_male", name: "doubled_male_sign", tags: ["color_male_male"], nameUnicode: "DOUBLED MALE SIGN", width: "+0.5ex" },
    { symbol: "⚤", unicodeHex: "26A4", code: 9892, alias: "female_male", name: "interlocked_female_and_male_sign", tags: ["color_female_male"], nameUnicode: "INTERLOCKED FEMALE AND MALE SIGN", width: "+0.5ex" },
    { symbol: "⚥", unicodeHex: "26A5", code: 9893, alias: "hermaphrodite", name: "male_and_female_sign", tags: ["color_hermaphrodite"], nameUnicode: "MALE AND FEMALE SIGN", width: "+0.5ex" },
    { symbol: "⚦", unicodeHex: "26A6", code: 9894, alias: "male_stroke", name: "male_with_stroke_sign", tags: ["color_male_stroke"], nameUnicode: "MALE WITH STROKE SIGN", width: "+0.5ex" },
    { symbol: "⚧", unicodeHex: "26A7", code: 9895, alias: "transgender", name: "male_with_stroke_and_male_and_female_sign", tags: ["color_transgender"], nameUnicode: "MALE WITH STROKE AND MALE AND FEMALE SIGN", width: "+0.5ex" },
    { symbol: "⚨", unicodeHex: "26A8", code: 9896, alias: "male_stroke_v", name: "vertical_male_with_stroke_sign", tags: ["color_male_stroke_v"], nameUnicode: "VERTICAL MALE WITH STROKE SIGN", width: "+0.5ex" },
    { symbol: "⚩", unicodeHex: "26A9", code: 9897, alias: "male_stroke_h", name: "horizontal_male_with_stroke_sign", tags: ["color_male_stroke_h"], nameUnicode: "HORIZONTAL MALE WITH STROKE SIGN", width: "+0.5ex" },
    { symbol: "☿", unicodeHex: "263F", code: 9791, alias: "", name: "mercury", tags: ["color_mercury"], nameUnicode: "MERCURY", width: "+0.5ex" },
    { symbol: "♀", unicodeHex: "2640", code: 9792, alias: "venus", name: "venus", tags: ["color_venus"], nameUnicode: "FEMALE SIGN", width: "+0.5ex", },
    { symbol: "♂", unicodeHex: "2642", code: 9794, alias: "mars", name: "mars", tags: ["color_mars"], nameUnicode: "MALE SIGN", width: "+0.5ex" },
    { symbol: "♁", unicodeHex: "2641", code: 9793, alias: "", name: "earth", tags: ["color_earth"], nameUnicode: "EARTH", width: "+0.5ex" },
    { symbol: "♃", unicodeHex: "2643", code: 9795, alias: "", name: "jupiter", tags: ["color_jupiter"], nameUnicode: "JUPITER", width: "+0.5ex" },
    { symbol: "♄", unicodeHex: "2644", code: 9796, alias: "", name: "saturn", tags: ["color_saturn"], nameUnicode: "SATURN", width: "+0.5ex" },
    { symbol: "♅", unicodeHex: "2645", code: 9797, alias: "", name: "uranus", tags: ["color_uranus"], nameUnicode: "URANUS", width: "+0.5ex" },
    { symbol: "♆", unicodeHex: "2646", code: 9798, alias: "", name: "neptune", tags: ["color_neptune"], nameUnicode: "NEPTUNE", width: "+0.5ex" },
    { symbol: "♇", unicodeHex: "2647", code: 9799, alias: "", name: "pluto", tags: ["color_pluto"], nameUnicode: "PLUTO", width: "+0.5ex" },
    { symbol: "♔", unicodeHex: "2654", code: 9812, alias: "chess_king", name: "white_chess_king", tags: [], nameUnicode: "WHITE CHESS KING", width: "+0.5ex" },
    { symbol: "♕", unicodeHex: "2655", code: 9813, alias: "chess_queen", name: "white_chess_queen", tags: [], nameUnicode: "WHITE CHESS QUEEN", width: "+0.5ex" },
    { symbol: "♖", unicodeHex: "2656", code: 9814, alias: "chess_rook", name: "white_chess_rook", tags: [], nameUnicode: "WHITE CHESS ROOK", width: "+0.5ex" },
    { symbol: "♗", unicodeHex: "2657", code: 9815, alias: "chess_bishop", name: "white_chess_bishop", tags: [], nameUnicode: "WHITE CHESS BISHOP", width: "+0.5ex" },
    { symbol: "♘", unicodeHex: "2658", code: 9816, alias: "chess_knight", name: "white_chess_knight", tags: [], nameUnicode: "WHITE CHESS KNIGHT", width: "+0.5ex" },
    { symbol: "♙", unicodeHex: "2659", code: 9817, alias: "chess_pawn", name: "white_chess_pawn", tags: [], nameUnicode: "WHITE CHESS PAWN", width: "+0.5ex" },
    { symbol: "♚", unicodeHex: "265A", code: 9818, alias: "", name: "black_chess_king", tags: ["color_chess_king"], nameUnicode: "BLACK CHESS KING", width: "+0.5ex" },
    { symbol: "♛", unicodeHex: "265B", code: 9819, alias: "", name: "black_chess_queen", tags: ["color_chess_queen"], nameUnicode: "BLACK CHESS QUEEN", width: "+0.5ex" },
    { symbol: "♜", unicodeHex: "265C", code: 9820, alias: "", name: "black_chess_rook", tags: ["color_chess_rook"], nameUnicode: "BLACK CHESS ROOK", width: "+0.5ex" },
    { symbol: "♝", unicodeHex: "265D", code: 9821, alias: "", name: "black_chess_bishop", tags: ["color_chess_bishop"], nameUnicode: "BLACK CHESS BISHOP", width: "+0.5ex" },
    { symbol: "♞", unicodeHex: "265E", code: 9822, alias: "", name: "black_chess_knight", tags: ["color_chess_knight"], nameUnicode: "BLACK CHESS KNIGHT", width: "+0.5ex" },
    { symbol: "♟", unicodeHex: "265F", code: 9823, alias: "", name: "black_chess_pawn", tags: ["color_chess_pawn"], nameUnicode: "BLACK CHESS PAWN", width: "+0.5ex" },
    { symbol: "♠", unicodeHex: "2660", code: 9824, alias: "black_spades", name: "black_spade_suit", tags: ["color_spades"], nameUnicode: "BLACK SPADE SUIT", width: "+0.5ex" },
    { symbol: "♤", unicodeHex: "2664", code: 9828, alias: "spades", name: "white_spade_suit", tags: [], nameUnicode: "WHITE SPADE SUIT", width: "+0.5ex" },
    { symbol: "♦", unicodeHex: "2666", code: 9830, alias: "black_diamonds", name: "black_diamond_suit", tags: ["color_diamonds"], nameUnicode: "BLACK DIAMOND SUIT", width: "+0.5ex" },
    { symbol: "♢", unicodeHex: "2662", code: 9826, alias: "diamonds", name: "white_diamond_suit", tags: [], nameUnicode: "WHITE DIAMOND SUIT", width: "+0.5ex" },
    { symbol: "♣", unicodeHex: "2663", code: 9827, alias: "black_clubs", name: "black_club_suit", tags: ["color_clubs"], nameUnicode: "BLACK CLUB SUIT", width: "+0.5ex" },
    { symbol: "♧", unicodeHex: "2667", code: 9831, alias: "clubs", name: "white_club_suit", tags: [], nameUnicode: "WHITE CLUB SUIT", width: "+0.5ex" },
    { symbol: "♩", unicodeHex: "2669", code: 9833, alias: "", name: "quarter_note", tags: ["color_quarter_note"], nameUnicode: "QUARTER NOTE", width: "+0.5ex" },
    { symbol: "♪", unicodeHex: "266A", code: 9834, alias: "", name: "eighth_note", tags: ["color_eighth_note"], nameUnicode: "EIGHTH NOTE", width: "+0.5ex" },
    { symbol: "♫", unicodeHex: "266B", code: 9835, alias: "two_notes", name: "beamed_eighth_notes", tags: ["color_two_notes"], nameUnicode: "BEAMED EIGHTH NOTES", width: "+0.5ex" },
    { symbol: "♬", unicodeHex: "266C", code: 9836, alias: "sixteenth_notes", name: "beamed_sixteenth_notes", tags: ["color_sixteenth_notes"], nameUnicode: "BEAMED SIXTEENTH NOTES", width: "+0.5ex" },
    { symbol: "♭", unicodeHex: "266D", code: 9837, alias: "flat", name: "music_flat_sign", tags: ["color_flat"], nameUnicode: "MUSIC FLAT SIGN", width: "+0.5ex" },
    { symbol: "♮", unicodeHex: "266E", code: 9838, alias: "natural", name: "music_natural_sign", tags: ["color_natural"], nameUnicode: "MUSIC NATURAL SIGN", width: "+0.5ex" },
    { symbol: "♯", unicodeHex: "266F", code: 9839, alias: "sharp", name: "music_sharp_sign", tags: ["color_sharp"], nameUnicode: "MUSIC SHARP SIGN", width: "+0.5ex" },
    { symbol: "♰", unicodeHex: "2670", code: 9840, alias: "west_cross", name: "west_syriac_cross", tags: ["color_west_cross"], nameUnicode: "WEST SYRIAC CROSS", width: "+0.5ex" },
    { symbol: "♱", unicodeHex: "2671", code: 9841, alias: "east_cross", name: "east_syriac_cross", tags: ["color_east_cross"], nameUnicode: "EAST SYRIAC CROSS", width: "+0.5ex" },
    { symbol: "♲", unicodeHex: "2672", code: 9842, alias: "recycle", name: "universal_recycling_symbol", tags: [], nameUnicode: "UNIVERSAL RECYCLING SYMBOL", width: "+0.6ex" },
    { symbol: "♳", unicodeHex: "2673", code: 9843, alias: "recycle_plastics_1", name: "recycling_symbol_for_type_1_plastics", tags: ["color_recycle_plastics_1"], nameUnicode: "RECYCLING SYMBOL FOR TYPE-1 PLASTICS", width: "+0.6ex" },
    { symbol: "♴", unicodeHex: "2674", code: 9844, alias: "recycle_plastics_2", name: "recycling_symbol_for_type_2_plastics", tags: ["color_recycle_plastics_2"], nameUnicode: "RECYCLING SYMBOL FOR TYPE-2 PLASTICS", width: "+0.6ex" },
    { symbol: "♵", unicodeHex: "2675", code: 9845, alias: "recycle_plastics_3", name: "recycling_symbol_for_type_3_plastics", tags: ["color_recycle_plastics_3"], nameUnicode: "RECYCLING SYMBOL FOR TYPE-3 PLASTICS", width: "+0.6ex" },
    { symbol: "♶", unicodeHex: "2676", code: 9846, alias: "recycle_plastics_4", name: "recycling_symbol_for_type_4_plastics", tags: ["color_recycle_plastics_4"], nameUnicode: "RECYCLING SYMBOL FOR TYPE-4 PLASTICS", width: "+0.6ex" },
    { symbol: "♷", unicodeHex: "2677", code: 9847, alias: "recycle_plastics_5", name: "recycling_symbol_for_type_5_plastics", tags: ["color_recycle_plastics_5"], nameUnicode: "RECYCLING SYMBOL FOR TYPE-5 PLASTICS", width: "+0.6ex" },
    { symbol: "♸", unicodeHex: "2678", code: 9848, alias: "recycle_plastics_6", name: "recycling_symbol_for_type_6_plastics", tags: ["color_recycle_plastics_6"], nameUnicode: "RECYCLING SYMBOL FOR TYPE-6 PLASTICS", width: "+0.6ex" },
    { symbol: "♹", unicodeHex: "2679", code: 9849, alias: "recycle_plastics_7", name: "recycling_symbol_for_type_7_plastics", tags: ["color_recycle_plastics_7"], nameUnicode: "RECYCLING SYMBOL FOR TYPE-7 PLASTICS", width: "+0.6ex" },
    { symbol: "♺", unicodeHex: "267A", code: 9850, alias: "recycle_generic_materials", name: "recycling_symbol_for_generic_materials", tags: ["color_recycle_generic_materials"], nameUnicode: "RECYCLING SYMBOL FOR GENERIC MATERIALS", width: "+0.6ex" },
    { symbol: "♻", unicodeHex: "267B", code: 9851, alias: "black_recycle", name: "black_universal_recycling_symbol", tags: ["color_recycle"], nameUnicode: "BLACK UNIVERSAL RECYCLING SYMBOL", width: "+0.6ex" },
    { symbol: "♼", unicodeHex: "267C", code: 9852, alias: "recycled_paper", name: "recycled_paper_symbol", tags: ["color_recycled_paper"], nameUnicode: "RECYCLED PAPER SYMBOL", width: "+0.6ex" },
    { symbol: "♽", unicodeHex: "267D", code: 9853, alias: "partially_recycled_paper", name: "partially_recycled_paper_symbol", tags: ["color_partially_recycled_paper"], nameUnicode: "PARTIALLY-RECYCLED PAPER SYMBOL", width: "+0.6ex" },
    { symbol: "♾", unicodeHex: "267E", code: 9854, alias: "acid_free", name: "permanent_paper_sign", tags: ["color_acid_free"], nameUnicode: "PERMANENT PAPER SIGN", width: "+0.5ex" },
    { symbol: "♿", unicodeHex: "267F", code: 9855, alias: "wheelchair", name: "wheelchair_symbol", tags: ["color_wheelchair"], nameUnicode: "WHEELCHAIR SYMBOL", width: "+0.5ex" },
    { symbol: "⚀", unicodeHex: "2680", code: 9856, alias: "dice_1", name: "die_face_1", tags: ["color_dice_1"], nameUnicode: "DIE FACE-1", width: "+0.5ex" },
    { symbol: "⚁", unicodeHex: "2681", code: 9857, alias: "dice_2", name: "die_face_2", tags: ["color_dice_2"], nameUnicode: "DIE FACE-2", width: "+0.5ex" },
    { symbol: "⚂", unicodeHex: "2682", code: 9858, alias: "dice_3", name: "die_face_3", tags: ["color_dice_3"], nameUnicode: "DIE FACE-3", width: "+0.5ex" },
    { symbol: "⚃", unicodeHex: "2683", code: 9859, alias: "dice_4", name: "die_face_4", tags: ["color_dice_4"], nameUnicode: "DIE FACE-4", width: "+0.5ex" },
    { symbol: "⚄", unicodeHex: "2684", code: 9860, alias: "dice_5", name: "die_face_5", tags: ["color_dice_5"], nameUnicode: "DIE FACE-5", width: "+0.5ex" },
    { symbol: "⚅", unicodeHex: "2685", code: 9861, alias: "dice_6", name: "die_face_6", tags: ["color_dice_6"], nameUnicode: "DIE FACE-6", width: "+0.5ex" },
    { symbol: "⚆", unicodeHex: "2686", code: 9862, alias: "circled_right_dot", name: "white_circle_with_dot_right", tags: [], nameUnicode: "WHITE CIRCLE WITH DOT RIGHT", width: "+0.5ex" },
    { symbol: "⚇", unicodeHex: "2687", code: 9863, alias: "circled_two_dots", name: "white_circle_with_two_dots", tags: [], nameUnicode: "WHITE CIRCLE WITH TWO DOTS", width: "+0.5ex" },
    { symbol: "⚈", unicodeHex: "2688", code: 9864, alias: "black_circled_right_dot", name: "black_circle_with_white_dot_right", tags: ["color_circled_right_dot"], nameUnicode: "BLACK CIRCLE WITH WHITE DOT RIGHT", width: "+0.5ex" },
    { symbol: "⚉", unicodeHex: "2689", code: 9865, alias: "black_circled_two_dots", name: "black_circle_with_two_white_dots", tags: ["color_circled_two_dots"], nameUnicode: "BLACK CIRCLE WITH TWO WHITE DOTS", width: "+0.5ex" },
    { symbol: "⚐", unicodeHex: "2690", code: 9872, alias: "flag", name: "white_flag", tags: [], nameUnicode: "WHITE FLAG", width: "+0.5ex" },
    { symbol: "⚑", unicodeHex: "2691", code: 9873, alias: "", name: "black_flag", tags: ["color_flag"], nameUnicode: "BLACK FLAG", width: "+0.5ex" },
    { symbol: "⚔", unicodeHex: "2694", code: 9876, alias: "swords", name: "crossed_swords", tags: ["color_swords"], nameUnicode: "CROSSED SWORDS", width: "+0.5ex" },
    { symbol: "⚘", unicodeHex: "2698", code: 9880, alias: "", name: "flower", tags: ["color_flower"], nameUnicode: "FLOWER", width: "+0.5ex" },
    { symbol: "⚙", unicodeHex: "2699", code: 9881, alias: "", name: "gear", tags: ["color_gear"], nameUnicode: "GEAR", width: "+0.5ex" },
    { symbol: "⚚", unicodeHex: "269A", code: 9882, alias: "hermes", name: "staff_of_hermes", tags: ["color_hermes"], nameUnicode: "STAFF OF HERMES", width: "+0.5ex" },
    { symbol: "⚛", unicodeHex: "269B", code: 9883, alias: "atom", name: "atom_symbol", tags: ["color_atom"], nameUnicode: "ATOM SYMBOL", width: "+0.5ex" },
    { symbol: "⚝", unicodeHex: "269D", code: 9885, alias: "outlined_star", name: "outlined_white_star", tags: ["color_outlined_star"], nameUnicode: "OUTLINED WHITE STAR", width: "+0.5ex" },
    { symbol: "⚠", unicodeHex: "26A0", code: 9888, alias: "warning", name: "warning_sign", tags: ["color_warning"], nameUnicode: "WARNING SIGN", width: "+0.5ex" },
    { symbol: "⚬", unicodeHex: "26AC", code: 9900, alias: "medium_small_circle", name: "medium_small_white_circle", tags: ["color_medium_small_circle"], nameUnicode: "MEDIUM SMALL WHITE CIRCLE", width: "+0.5ex" },
    { symbol: "⚭", unicodeHex: "26AD", code: 9901, alias: "marriage", name: "marriage_symbol", tags: ["color_marriage"], nameUnicode: "MARRIAGE SYMBOL", width: "+0.5ex" },
    { symbol: "⚮", unicodeHex: "26AE", code: 9902, alias: "divorce", name: "divorce_symbol", tags: ["color_divorce"], nameUnicode: "DIVORCE SYMBOL", width: "+0.8ex" },
    { symbol: "⚯", unicodeHex: "26AF", code: 9903, alias: "unmarried_partnership", name: "unmarried_partnership_symbol", tags: ["color_unmarried_partnership"], nameUnicode: "UNMARRIED PARTNERSHIP SYMBOL", width: "+1ex" },
    { symbol: "⚲", unicodeHex: "26B2", code: 9906, alias: "", name: "neuter", tags: ["color_neuter"], nameUnicode: "NEUTER", width: "+0.5ex" },
    { symbol: "⚳", unicodeHex: "26B3", code: 9907, alias: "", name: "ceres", tags: ["color_ceres"], nameUnicode: "CERES", width: "+0.5ex" },
    { symbol: "⚴", unicodeHex: "26B4", code: 9908, alias: "", name: "pallas", tags: ["color_pallas"], nameUnicode: "PALLAS", width: "+0.5ex" },
    { symbol: "⚵", unicodeHex: "26B5", code: 9909, alias: "", name: "juno", tags: ["color_juno"], nameUnicode: "JUNO", width: "+0.5ex" },
    { symbol: "⚶", unicodeHex: "26B6", code: 9910, alias: "", name: "vesta", tags: ["color_vesta"], nameUnicode: "VESTA", width: "+0.5ex" },
    { symbol: "⚷", unicodeHex: "26B7", code: 9911, alias: "", name: "chiron", tags: ["color_chiron"], nameUnicode: "CHIRON", width: "+0.5ex" },
    { symbol: "⚹", unicodeHex: "26B9", code: 9913, alias: "", name: "sextile", tags: ["color_sextile"], nameUnicode: "SEXTILE", width: "+0.5ex" },
    { symbol: "⚿", unicodeHex: "26BF", code: 9919, alias: "", name: "squared_key", tags: ["color_squared_key"], nameUnicode: "SQUARED KEY", width: "+0.5ex" },
    { symbol: "⛀", unicodeHex: "26C0", code: 9920, alias: "draughts_man", name: "white_draughts_man", tags: [], nameUnicode: "WHITE DRAUGHTS MAN", width: "+0.5ex" },
    { symbol: "⛁", unicodeHex: "26C1", code: 9921, alias: "draughts_king", name: "white_draughts_king", tags: [], nameUnicode: "WHITE DRAUGHTS KING", width: "+0.5ex" },
    { symbol: "⛂", unicodeHex: "26C2", code: 9922, alias: "", name: "black_draughts_man", tags: ["color_draughts_man"], nameUnicode: "BLACK DRAUGHTS MAN", width: "+0.5ex" },
    { symbol: "⛃", unicodeHex: "26C3", code: 9923, alias: "", name: "black_draughts_king", tags: ["color_draughts_king"], nameUnicode: "BLACK DRAUGHTS KING", width: "+0.5ex" },
    { symbol: "⛆", unicodeHex: "26C6", code: 9926, alias: "", name: "rain", tags: ["color_rain"], nameUnicode: "RAIN", width: "+0.5ex" },
    { symbol: "⛇", unicodeHex: "26C7", code: 9927, alias: "", name: "black_snowman", tags: ["color_snowman"], nameUnicode: "BLACK SNOWMAN", width: "+0.5ex" },
    { symbol: "⛉", unicodeHex: "26C9", code: 9929, alias: "turned_shogi_piece", name: "turned_white_shogi_piece", tags: [], nameUnicode: "TURNED WHITE SHOGI PIECE", width: "+0.5ex" },
    { symbol: "⛊", unicodeHex: "26CA", code: 9930, alias: "black_turned_shogi_piece", name: "turned_black_shogi_piece", tags: ["color_turned_shogi_piece"], nameUnicode: "TURNED BLACK SHOGI PIECE", width: "+0.5ex" },
    { symbol: "⛋", unicodeHex: "26CB", code: 9931, alias: "squared_diamond", name: "white_diamond_in_square", tags: ["color_squared_diamond"], nameUnicode: "WHITE DIAMOND IN SQUARE", width: "+0.5ex" },
    { symbol: "⛌", unicodeHex: "26CC", code: 9932, alias: "", name: "crossing_lanes", tags: ["color_crossing_lanes"], nameUnicode: "CROSSING LANES", width: "+0.5ex", },
    { symbol: "⛍", unicodeHex: "26CD", code: 9933, alias: "", name: "disabled_car", tags: ["color_disabled_car"], nameUnicode: "DISABLED CAR", width: "+0.5ex" },
    { symbol: "⛐", unicodeHex: "26D0", code: 9936, alias: "sliding_car", name: "car_sliding", tags: ["color_sliding_car"], nameUnicode: "CAR SLIDING", width: "+0.5ex" },
    { symbol: "⛒", unicodeHex: "26D2", code: 9938, alias: "", name: "circled_crossing_lanes", tags: ["color_circled_crossing_lanes"], nameUnicode: "CIRCLED CROSSING LANES", width: "+0.5ex" },
    { symbol: "⛟", unicodeHex: "26DF", code: 9951, alias: "", name: "black_truck", tags: ["color_truck"], nameUnicode: "BLACK TRUCK", width: "+0.5ex" },
    { symbol: "⛤", unicodeHex: "26E4", code: 9956, alias: "", name: "pentagram", tags: ["color_pentagram"], nameUnicode: "PENTAGRAM", width: "+0.5ex" },
    { symbol: "⛧", unicodeHex: "26E7", code: 9959, alias: "", name: "inverted_pentagram", tags: ["color_inverted_pentagram"], nameUnicode: "INVERTED PENTAGRAM", width: "+0.5ex" },
    { symbol: "⛩", unicodeHex: "26E9", code: 9961, alias: "", name: "shinto_shrine", tags: ["color_shinto_shrine"], nameUnicode: "SHINTO SHRINE", width: "+0.5ex" },
    { symbol: "⛫", unicodeHex: "26EB", code: 9963, alias: "", name: "castle", tags: ["color_castle"], nameUnicode: "CASTLE", width: "+0.5ex" },
    { symbol: "⛬", unicodeHex: "26EC", code: 9964, alias: "", name: "historic_site", tags: ["color_historic_site"], nameUnicode: "HISTORIC SITE", width: "+0.5ex" },
    { symbol: "⛭", unicodeHex: "26ED", code: 9965, alias: "", name: "gear_without_hub", tags: ["color_gear_without_hub"], nameUnicode: "GEAR WITHOUT HUB", width: "+0.5ex" },
    { symbol: "⛮", unicodeHex: "26EE", code: 9966, alias: "", name: "gear_with_handles", tags: ["color_gear_with_handles"], nameUnicode: "GEAR WITH HANDLES", width: "+0.5ex" },
    { symbol: "⛯", unicodeHex: "26EF", code: 9967, alias: "map_lighthouse", name: "map_symbol_for_lighthouse", tags: ["color_map_lighthouse"], nameUnicode: "MAP SYMBOL FOR LIGHTHOUSE", width: "+0.5ex" },
    { symbol: "⛱", unicodeHex: "26F1", code: 9969, alias: "", name: "umbrella_on_ground", tags: ["color_umbrella_on_ground"], nameUnicode: "UMBRELLA ON GROUND", width: "+0.5ex" },
    { symbol: "⛶", unicodeHex: "26F6", code: 9974, alias: "", name: "square_four_corners", tags: ["color_square_four_corners"], nameUnicode: "SQUARE FOUR CORNERS", width: "+0.5ex" },
    { symbol: "⛸", unicodeHex: "26F8", code: 9976, alias: "", name: "ice_skate", tags: ["color_ice_skate"], nameUnicode: "ICE SKATE", width: "+0.5ex" },
    { symbol: "⛻", unicodeHex: "26FB", code: 9979, alias: "japanese_bank", name: "japanese_bank_symbol", tags: ["color_japanese_bank"], nameUnicode: "JAPANESE BANK SYMBOL", width: "+0.5ex" },
    { symbol: "⛾", unicodeHex: "26FE", code: 9982, alias: "black_squared_cup", name: "cup_on_black_square", tags: ["color_squared_cup"], nameUnicode: "CUP ON BLACK SQUARE", width: "+0.5ex" },
    { symbol: "☺", unicodeHex: "263A", code: 9786, alias: "relaxed", name: "relaxed", tags: ["color_relaxed"], nameUnicode: "relaxed", width: "+0.5ex" },
    { symbol: "☹", unicodeHex: "2639", code: 9785, alias: "frowning_face", name: "frowning_face", tags: ["color_frowning_face"], nameUnicode: "frowning_face", width: "+0.5ex" },
    { symbol: "♨", unicodeHex: "2668", code: 9832, alias: "hotsprings", name: "hotsprings", tags: ["color_hotsprings"], nameUnicode: "hotsprings", width: "+0.5ex" },
    { symbol: "©", unicodeHex: "A9", code: 169, alias: "copyright", name: "copyright", tags: ["color_copyright"], nameUnicode: "Copyright Sign", width: "+0.5ex" },
    { symbol: "™", unicodeHex: "2122", code: 8482, alias: "tm", name: "tm", tags: ["color_tm"], nameUnicode: "Trade Mark Sign", width: "+0.5ex" },
    { symbol: "®", unicodeHex: "AE", code: 174, alias: "registered", name: "registered", tags: ["color_registered"], nameUnicode: "Registered Sign", width: "+0.5ex" },
    { symbol: "〰", unicodeHex: "3030", code: 12336, alias: "wavy_dash", name: "wavy_dash", tags: ["color_wavy_dash"], nameUnicode: "Wavy Das", width: "+0.5ex" },
    { symbol: "✔", unicodeHex: "2714", code: 10004, alias: "heavy_check_mark", name: "heavy_check_mark", tags: ["color_heavy_check_mark"], nameUnicode: "Heavy Check Mark", width: "+0.5ex" },
    { symbol: "☑", unicodeHex: "2611", code: 9745, alias: "ballot_box_with_check", name: "ballot_box_with_check", tags: ["color_ballot_box_with_check"], nameUnicode: "Ballot Box with Check", width: "+0.5ex" },
    { symbol: "❇", unicodeHex: "2747", code: 10055, alias: "sparkle", name: "sparkle", tags: ["color_sparkle"], nameUnicode: "sparkle", width: "+0.5ex" },
    { symbol: "✳", unicodeHex: "2733", code: 10035, alias: "eight_spoked_asterisk", name: "eight_spoked_asterisk", tags: ["color_eight_spoked_asterisk"], nameUnicode: "eight spoked asterisk", width: "+0.5ex" },
    { symbol: "Ⓜ", unicodeHex: "24C2", code: 9410, alias: "m", name: "m", tags: ["color_m"], nameUnicode: "Circled Latin Capital Letter M", width: "+0.5ex" },
    { symbol: "◦", unicodeHex: "25E6", code: 8729, alias: "bullet_o", name: "white_bullet", tags: ["color_bullet_o"], nameUnicode: "WHITE BULLET", width: "+0.5ex" },
    { symbol: "⁃", unicodeHex: "2043", code: 8259, alias: "hyphen_bullet", name: "hyphen_bullet", tags: ["color_hyphen_bullet"], nameUnicode: "HYPHEN BULLET", width: "+0.5ex" },
    { symbol: "↔", unicodeHex: "2194", code: 8596, alias: "left_right_arrow", name: "left_right_arrow", tags: ["color_left_right_arrow"], nameUnicode: "LEFT RIGHT ARROW", width: "+0.5ex" },
    { symbol: "↕", unicodeHex: "2195", code: 8597, alias: "up_down_arrow", name: "up_down_arrow", tags: ["color_up_down_arrow"], nameUnicode: "UP DOWN ARROW", width: "+0.5ex" },
    { symbol: "↖", unicodeHex: "2196", code: 8598, alias: "nw_arrow", name: "north_west_arrow", tags: ["color_nw_arrow"], nameUnicode: "NORTH WEST ARROW", width: "+0.5ex" },
    { symbol: "↗", unicodeHex: "2197", code: 8599, alias: "ne_arrow", name: "north_east_arrow", tags: ["color_ne_arrow"], nameUnicode: "NORTH EAST ARROW", width: "+0.5ex" },
    { symbol: "↘", unicodeHex: "2198", code: 8600, alias: "se_arrow", name: "south_east_arrow", tags: ["color_se_arrow"], nameUnicode: "SOUTH EAST ARROW", width: "+0.5ex" },
    { symbol: "↙", unicodeHex: "2199", code: 8601, alias: "sw_arrow", name: "south_west_arrow", tags: ["color_sw_arrow"], nameUnicode: "SOUTH WEST ARROW", width: "+0.5ex" },
    { symbol: "⤡", unicodeHex: "2921", code: 10529, alias: "nw_se_arrow", name: "north_west_and_south_east_arrow", tags: ["color_nw_se_arrow"], nameUnicode: "NORTH WEST AND SOUTH EAST ARROW", width: "+0.5ex" },
    { symbol: "⤢", unicodeHex: "2922", code: 10530, alias: "ne_sw_arrow", name: "north_east_and_south_west_arrow", tags: ["color_ne_sw_arrow"], nameUnicode: "NORTH EAST AND SOUTH WEST ARROW", width: "+0.5ex" },
    { symbol: "⇦", unicodeHex: "21E6", code: 8678, alias: "left_fill_arrow_o", name: "leftwards_white_arrow", tags: ["color_left_fill_arrow_o"], nameUnicode: "LEFTWARDS WHITE ARROW", width: "+0.5ex" },
    { symbol: "⇧", unicodeHex: "21E7", code: 8679, alias: "up_fill_arrow_o", name: "upwards_white_arrow", tags: ["color_up_fill_arrow_o"], nameUnicode: "UPWARDS WHITE ARROW", width: "+0.5ex" },
    { symbol: "⇨", unicodeHex: "21E8", code: 8680, alias: "right_fill_arrow_o", name: "rightwards_white_arrow", tags: ["color_right_fill_arrow_o"], nameUnicode: "RIGHTWARDS WHITE ARROW", width: "+0.5ex" },
    { symbol: "⇩", unicodeHex: "21E9", code: 8681, alias: "down_fill_arrow_o", name: "downwards_white_arrow", tags: ["color_down_fill_arrow_o"], nameUnicode: "DOWNWARDS WHITE ARROW", width: "+0.5ex" },
    { symbol: "⬄", unicodeHex: "2B04", code: 11012, alias: "left_right_fill_arrow_o", name: "left_right_white_arrow", tags: ["color_left_right_fill_arrow_o"], nameUnicode: "LEFT RIGHT WHITE ARROW", width: "+0.5ex" },
    { symbol: "⇳", unicodeHex: "21F3", code: 8691, alias: "up_down_fill_arrow_o", name: "up_down_white_arrow", tags: ["color_up_down_fill_arrow_o"], nameUnicode: "UP DOWN WHITE ARROW", width: "+0.5ex" },
    { symbol: "⬅", unicodeHex: "2B05", code: 11077, alias: "left_fill_arrow", name: "leftwards_black_arrow", tags: ["color_left_fill_arrow"], nameUnicode: "LEFTWARDS BLACK ARROW", width: "+0.5ex" },
    { symbol: "⬆", unicodeHex: "2191", code: 8593, alias: "up_fill_arrow", name: "upwards_black_arrow", tags: ["color_up_fill_arrow"], nameUnicode: "UPWARDS BLACK ARROW", width: "+0.5ex" },
    { symbol: "➡", unicodeHex: "27A1", code: 10145, alias: "right_fill_arrow", name: "rightwards_black_arrow", tags: ["color_right_fill_arrow"], nameUnicode: "RIGHTWARDS BLACK ARROW", width: "+0.5ex" },
    { symbol: "⬇", unicodeHex: "2193", code: 8595, alias: "down_fill_arrow", name: "downwards_black_arrow", tags: ["color_down_fill_arrow"], nameUnicode: "DOWNWARDS BLACK ARROW", width: "+0.5ex" },
    { symbol: "⬌", unicodeHex: "2B8C", code: 11148, alias: "left_right_fill_arrow", name: "left_right_black_arrow", tags: ["color_left_right_fill_arrow"], nameUnicode: "LEFT RIGHT BLACK ARROW", width: "+0.5ex" },
    { symbol: "⬍", unicodeHex: "2B8D", code: 11149, alias: "up_down_fill_arrow", name: "up_down_black_arrow", tags: ["color_up_down_fill_arrow"], nameUnicode: "UP DOWN BLACK ARROW", width: "+0.5ex" },
    { symbol: "⬀", unicodeHex: "2B80", code: 11136, alias: "ne_fill_arrow_o", name: "north_east_white_arrow", tags: ["color_ne_fill_arrow_o"], nameUnicode: "NORTH EAST WHITE ARROW", width: "+0.5ex" },
    { symbol: "⬁", unicodeHex: "2B81", code: 11137, alias: "nw_fill_arrow_o", name: "north_west_white_arrow", tags: ["color_nw_fill_arrow_o"], nameUnicode: "NORTH WEST WHITE ARROW", width: "+0.5ex" },
    { symbol: "⬂", unicodeHex: "2B82", code: 11138, alias: "se_fill_arrow_o", name: "south_east_white_arrow", tags: ["color_se_fill_arrow_o"], nameUnicode: "SOUTH EAST WHITE ARROW", width: "+0.5ex" },
    { symbol: "⬃", unicodeHex: "2B83", code: 11139, alias: "sw_fill_arrow_o", name: "south_west_white_arrow", tags: ["color_sw_fill_arrow_o"], nameUnicode: "SOUTH WEST WHITE ARROW", width: "+0.5ex" },
    { symbol: "⬈", unicodeHex: "2B88", code: 11144, alias: "ne_fill_arrow", name: "north_east_black_arrow", tags: ["color_ne_fill_arrow"], nameUnicode: "NORTH EAST BLACK ARROW", width: "+0.5ex" },
    { symbol: "⬉", unicodeHex: "2B89", code: 11145, alias: "nw_fill_arrow", name: "north_west_black_arrow", tags: ["color_nw_fill_arrow"], nameUnicode: "NORTH WEST BLACK ARROW", width: "+0.5ex" },
    { symbol: "⬊", unicodeHex: "2B8A", code: 11146, alias: "se_fill_arrow", name: "south_east_black_arrow", tags: ["color_se_fill_arrow"], nameUnicode: "SOUTH EAST BLACK ARROW", width: "+0.5ex" },
    { symbol: "⬋", unicodeHex: "2B8B", code: 11147, alias: "sw_fill_arrow", name: "south_west_black_arrow", tags: ["color_sw_fill_arrow"], nameUnicode: "SOUTH WEST BLACK ARROW", width: "+0.5ex" },
    { symbol: "↵", unicodeHex: "21B5", code: 8629, alias: "down_left_arrow", name: "downwards_left_corner_arrow", tags: ["color_down_left_arrow"], nameUnicode: "DOWNWARDS ARROW WITH CORNER LEFTWARDS", width: "+0.5ex" },
    { symbol: "↳", unicodeHex: "21B3", code: 8627, alias: "down_right_arrow", name: "downwards_right_corner_arrow", tags: ["color_down_right_arrow"], nameUnicode: "DOWNWARDS ARROW WITH TIP RIGHTWARDS", width: "+0.5ex" },
    { symbol: "➮", unicodeHex: "27AE", code: 10142, alias: "upper_shadow_right_arrow", name: "heavy_upper_right_shadowed_white_rightwards_arrow", tags: ["color_upper_shadow_right_arrow"], nameUnicode: "HEAVY UPPER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW", width: "+0.5ex" },
    { symbol: "➭", unicodeHex: "279D", code: 10141, alias: "lower_shadow_right_arrow", name: "heavy_lower_right_shadowed_white_rightwards_arrow", tags: ["color_lower_shadow_right_arrow"], nameUnicode: "HEAVY LOWER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW", width: "+0.5ex" },
    { symbol: "➯", unicodeHex: "279F", code: 10143, alias: "notched_lower_shadow_right_arrow", name: "notched_lower_right_shadowed_white_rightwards_arrow", tags: ["color_notched_lower_shadow_right_arrow"], nameUnicode: "NOTCHED LOWER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW", width: "+0.5ex" },
    { symbol: "➱", unicodeHex: "27B1", code: 10145, alias: "notched_upper_shadow_right_arrow", name: "notched_upper_right_shadowed_white_rightwards_arrow", tags: ["color_notched_upper_shadow_right_arrow"], nameUnicode: "NOTCHED UPPER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW", width: "+0.5ex" },
    { symbol: "➲", unicodeHex: "27B2", code: 10162, alias: "circled_heavy_right_arrow", name: "circled_heavy_white_rightwards_arrow", tags: ["color_circled_heavy_right_arrow"], nameUnicode: "CIRCLED HEAVY WHITE RIGHTWARDS ARROW", width: "+0.5ex" },
    { symbol: "❍", unicodeHex: "274D", code: 10061, alias: "shadowed_circle", name: "shadowed_white_circle", tags: ["color_shadowed_circle"], nameUnicode: "SHADOWED WHITE CIRCLE", width: "+0.5ex" },
    { symbol: "❏", unicodeHex: "274F", code: 10063, alias: "lower_right_shadow_square", name: "lower_right_drop_shadowed_white_square", tags: ["color_lower_right_shadow_square"], nameUnicode: "LOWER RIGHT DROP-SHADOWED WHITE SQUARE", width: "+0.5ex" },
    { symbol: "❐", unicodeHex: "2750", code: 10064, alias: "upper_right_shadow_square", name: "upper_right_drop_shadowed_white_square", tags: ["color_upper_right_shadow_square"], nameUnicode: "UPPER RIGHT DROP-SHADOWED WHITE SQUARE", width: "+0.5ex" },
    { symbol: "❑", unicodeHex: "2751", code: 10065, alias: "lower_right_shadow_square", name: "lower_right_shadowed_white_square", tags: ["color_lower_right_shadow_square"], nameUnicode: "LOWER RIGHT SHADOWED WHITE SQUARE", width: "+0.5ex" },
    { symbol: "❒", unicodeHex: "2752", code: 10066, alias: "upper_right_shadow_square", name: "upper_right_shadowed_white_square", tags: ["color_upper_right_shadow_square"], nameUnicode: "UPPER RIGHT SHADOWED WHITE SQUARE", width: "+0.5ex" },
    { symbol: "➤", unicodeHex: "27A4", code: 10148, alias: "black_right_arrowhead", name: "black_rightwards_arrowhead", tags: ["color_right_arrowhead"], nameUnicode: "BLACK RIGHTWARDS ARROWHEAD", width: "+0.5ex" },
    { symbol: "➢", unicodeHex: "27A2", code: 10146, alias: "top_lighted_right_arrowhead", name: "3d_top_lighted_right_arrowhead", tags: ["color_top_lighted_right_arrowhead"], nameUnicode: "THREE-D TOP-LIGHTED RIGHTWARDS ARROWHEAD", width: "+0.5ex" },
    { symbol: "➣", unicodeHex: "27A3", code: 10147, alias: "bottom_lighted_right_arrowhead", name: "3d_bottom_lighted_right_arrowhead", tags: ["color_bottom_lighted_right_arrowhead"], nameUnicode: "THREE-D BOTTOM-LIGHTED RIGHTWARDS ARROWHEAD", width: "+0.5ex" },
    { symbol: "□", unicodeHex: "25A1", code: 9633, alias: "square", name: "white_square", tags: [], nameUnicode: "WHITE SQUARE", width: "+0.5ex" },
    { symbol: "▪", unicodeHex: "25AA", code: 9642, alias: "black_small_square", name: "black_small_square", tags: ["color_small_square"], nameUnicode: "BLACK SMALL SQUARE", width: "+0.5ex" },
    { symbol: "▫", unicodeHex: "25AB", code: 9643, alias: "small_square", name: "white_small_square", tags: [], nameUnicode: "WHITE SMALL SQUARE", width: "+0.5ex" },
    { symbol: "◻", unicodeHex: "25FB", code: 9611, alias: "medium_square", name: "white_medium_square", tags: [], nameUnicode: "WHITE MEDIUM SQUARE", width: "+0.5ex" },
    { symbol: "◼", unicodeHex: "25FC", code: 9612, alias: "black_medium_square", name: "black_medium_square", tags: ["color_medium_square"], nameUnicode: "BLACK MEDIUM SQUARE", width: "+0.5ex" },
    { symbol: "⬒", unicodeHex: "2B12", code: 11026, alias: "square_top_fill", name: "square_with_top_half_black", tags: ["color_square_top_fill"], nameUnicode: "SQUARE WITH TOP HALF BLACK", width: "+0.5ex" },
    { symbol: "⬓", unicodeHex: "2B13", code: 11027, alias: "square_bottom_fill", name: "square_with_bottom_half_black", tags: ["color_square_bottom_fill"], nameUnicode: "SQUARE WITH BOTTOM HALF BLACK", width: "+0.5ex" },
    { symbol: "⬔", unicodeHex: "2B14", code: 11028, alias: "square_right_fill", name: "square_with_upper_right_diagonal_half_black", tags: ["color_square_right_fill"], nameUnicode: "SQUARE WITH UPPER RIGHT DIAGONAL HALF BLACK", width: "+0.5ex" },
    { symbol: "⬕", unicodeHex: "2B15", code: 11029, alias: "square_left_fill", name: "square_with_lower_left_diagonal_half_black", tags: ["color_square_left_fill"], nameUnicode: "SQUARE WITH LOWER LEFT DIAGONAL HALF BLACK", width: "+0.5ex" },
    { symbol: "◢", unicodeHex: "25E2", code: 9698, alias: "black_triangle_lower_right", name: "black_lower_right_triangle", tags: ["color_triangle_lower_right"], nameUnicode: "BLACK LOWER RIGHT TRIANGLE", width: "+0.5ex" },
    { symbol: "◣", unicodeHex: "25E3", code: 9699, alias: "black_triangle_lower_left", name: "black_lower_left_triangle", tags: ["color_triangle_lower_left"], nameUnicode: "BLACK LOWER LEFT TRIANGLE", width: "+0.5ex" },
    { symbol: "◤", unicodeHex: "25E4", code: 9700, alias: "black_triangle_upper_left", name: "black_upper_left_triangle", tags: ["color_triangle_upper_left"], nameUnicode: "BLACK UPPER LEFT TRIANGLE", width: "+0.5ex" },
    { symbol: "◥", unicodeHex: "25E5", code: 9701, alias: "black_triangle_upper_right", name: "black_upper_right_triangle", tags: ["color_triangle_upper_right"], nameUnicode: "BLACK UPPER RIGHT TRIANGLE", width: "+0.5ex" },
    { symbol: "◿", unicodeHex: "25FF", code: 9727, alias: "triangle_lower_right", name: "lower_right_triangle", tags: [], nameUnicode: "LOWER RIGHT TRIANGLE", width: "+0.5ex" },
    { symbol: "◺", unicodeHex: "25FA", code: 9722, alias: "triangle_lower_left", name: "lower_left_triangle", tags: [], nameUnicode: "LOWER LEFT TRIANGLE", width: "+0.5ex" },
    { symbol: "◸", unicodeHex: "25F8", code: 9720, alias: "triangle_upper_left", name: "upper_left_triangle", tags: [], nameUnicode: "UPPER LEFT TRIANGLE", width: "+0.5ex" },
    { symbol: "◹", unicodeHex: "25F9", code: 9721, alias: "triangle_upper_right", name: "upper_right_triangle", tags: [], nameUnicode: "UPPER RIGHT TRIANGLE", width: "+0.5ex" },
    { symbol: "▴", unicodeHex: "25B4", code: 9652, alias: "black_small_triangle", name: "black_up_pointing_small_triangle", tags: ["color_small_triangle"], nameUnicode: "BLACK UP-POINTING SMALL TRIANGLE", width: "+0.5ex" },
    { symbol: "▵", unicodeHex: "25B5", code: 9653, alias: "small_triangle", name: "white_up_pointing_small_triangle", tags: [], nameUnicode: "WHITE UP-POINTING SMALL TRIANGLE", width: "+0.5ex" },
    { symbol: "▸", unicodeHex: "25B8", code: 9656, alias: "black_small_triangle_right", name: "black_right_pointing_small_triangle", tags: ["color_small_triangle_right"], nameUnicode: "BLACK RIGHT-POINTING SMALL TRIANGLE", width: "+0.5ex" },
    { symbol: "▹", unicodeHex: "25B9", code: 9657, alias: "small_triangle_right", name: "white_right_pointing_small_triangle", tags: [], nameUnicode: "WHITE RIGHT-POINTING SMALL TRIANGLE", width: "+0.5ex" },
    { symbol: "▾", unicodeHex: "25BE", code: 9662, alias: "black_small_triangle_down", name: "black_down_pointing_small_triangle", tags: ["color_small_triangle_down"], nameUnicode: "BLACK DOWN-POINTING SMALL TRIANGLE", width: "+0.5ex" },
    { symbol: "▿", unicodeHex: "25BF", code: 9663, alias: "small_triangle_down", name: "white_down_pointing_small_triangle", tags: [], nameUnicode: "WHITE DOWN-POINTING SMALL TRIANGLE", width: "+0.5ex" },
    { symbol: "◂", unicodeHex: "25C2", code: 9666, alias: "black_small_triangle_left", name: "black_left_pointing_small_triangle", tags: ["color_small_triangle_left"], nameUnicode: "BLACK LEFT-POINTING SMALL TRIANGLE", width: "+0.5ex" },
    { symbol: "◃", unicodeHex: "25C3", code: 9667, alias: "small_triangle_left", name: "white_left_pointing_small_triangle", tags: [], nameUnicode: "WHITE LEFT-POINTING SMALL TRIANGLE", width: "+0.5ex" },
    { symbol: "►", unicodeHex: "25BA", code: 9658, alias: "black_right_pointer", name: "black_right_pointing_pointer", tags: ["color_right_pointer"], nameUnicode: "BLACK RIGHT-POINTING POINTER", width: "+0.5ex" },
    { symbol: "▻", unicodeHex: "25BB", code: 9659, alias: "right_pointer", name: "white_right_pointing_pointer", tags: [], nameUnicode: "WHITE RIGHT-POINTING POINTER", width: "+0.5ex" },
    { symbol: "◄", unicodeHex: "25C4", code: 9668, alias: "black_left_pointer", name: "black_left_pointing_pointer", tags: ["color_left_pointer"], nameUnicode: "BLACK LEFT-POINTING POINTER", width: "+0.5ex" },
    { symbol: "◅", unicodeHex: "25C5", code: 9669, alias: "left_pointer", name: "white_left_pointing_pointer", tags: [], nameUnicode: "WHITE LEFT-POINTING POINTER", width: "+0.5ex" },
    { symbol: "◯", unicodeHex: "25EF", code: 9711, alias: "large_circle", name: "large_circle", tags: [], nameUnicode: "LARGE CIRCLE", width: "+0.5ex" },
    { symbol: "⬤", unicodeHex: "2B24", code: 11036, alias: "black_large_circle", name: "black_large_circle", tags: ["color_large_circle"], nameUnicode: "BLACK LARGE CIRCLE", width: "+0.5ex" },
    { symbol: "◆", unicodeHex: "25C6", code: 9670, alias: "black_diamond", name: "black_diamond", tags: ["color_diamond"], nameUnicode: "BLACK DIAMOND", width: "+0.5ex" },
    { symbol: "◇", unicodeHex: "25C7", code: 9671, alias: "diamond", name: "white_diamond", tags: [], nameUnicode: "WHITE DIAMOND", width: "+0.5ex" },
    { symbol: "⬥", unicodeHex: "2B25", code: 11045, alias: "black_medium_diamond", name: "black_medium_diamond", tags: ["color_medium_diamond"], nameUnicode: "BLACK MEDIUM DIAMOND", width: "+0.5ex" },
    { symbol: "⬦", unicodeHex: "2B26", code: 11046, alias: "medium_diamond", name: "white_medium_diamond", tags: [], nameUnicode: "WHITE MEDIUM DIAMOND", width: "+0.5ex" },
    { symbol: "⬩", unicodeHex: "2B29", code: 11049, alias: "black_small_diamond", name: "black_small_diamond", tags: ["color_small_diamond"], nameUnicode: "BLACK SMALL DIAMOND", width: "+0.5ex" },
    { symbol: "⬖", unicodeHex: "2B16", code: 11030, alias: "diamond_left_fill", name: "diamond_with_left_half_black", tags: ["color_diamond_left_fill"], nameUnicode: "DIAMOND WITH LEFT HALF BLACK", width: "+0.5ex" },
    { symbol: "⬗", unicodeHex: "2B17", code: 11031, alias: "diamond_right_fill", name: "diamond_with_right_half_black", tags: ["color_diamond_right_fill"], nameUnicode: "DIAMOND WITH RIGHT HALF BLACK", width: "+0.5ex" },
    { symbol: "⬘", unicodeHex: "2B18", code: 11032, alias: "diamond_top_fill", name: "diamond_with_top_half_black", tags: ["color_diamond_top_fill"], nameUnicode: "DIAMOND WITH TOP HALF BLACK", width: "+0.5ex" },
    { symbol: "⬙", unicodeHex: "2B19", code: 11033, alias: "diamond_bottom_fill", name: "diamond_with_bottom_half_black", tags: ["color_diamond_bottom_fill"], nameUnicode: "DIAMOND WITH BOTTOM HALF BLACK", width: "+0.5ex" },
    { symbol: "⬪", unicodeHex: "2B2A", code: 11050, alias: "black_small_lozenge", name: "black_small_lozenge", tags: ["color_small_lozenge"], nameUnicode: "BLACK SMALL LOZENGE", width: "+0.5ex" },
    { symbol: "⬫", unicodeHex: "2B2B", code: 11051, alias: "small_lozenge", name: "white_small_lozenge", tags: [], nameUnicode: "WHITE SMALL LOZENGE", width: "+0.5ex" },
    { symbol: "◈", unicodeHex: "25C8", code: 9672, alias: "diamond_fill_small", name: "white_diamond_containing_black_small_diamond", tags: ["color_diamond_fill_small"], nameUnicode: "WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND", width: "+0.5ex" },
    { symbol: "❖", unicodeHex: "2756", code: 10070, alias: "black_diamond_white_x", name: "black_diamond_minus_white_x", tags: ["color_diamond_white_x"], nameUnicode: "BLACK DIAMOND MINUS WHITE X", width: "+0.5ex" },
    { symbol: "⟐", unicodeHex: "27D0", code: 10192, alias: "diamond_dot", name: "white_diamond_with_centred_dot", tags: ["color_diamond_dot"], nameUnicode: "WHITE DIAMOND WITH CENTRED DOT", width: "+0.5ex" },
    { symbol: "✠", unicodeHex: "2720", code: 10016, alias: "maltese_cross", name: "maltese_cross", tags: ["color_maltese_cross"], nameUnicode: "MALTESE CROSS", width: "+0.5ex" },
    { symbol: "⊞", unicodeHex: "229E", code: 8862, alias: "squared_plus", name: "squared_plus", tags: ["color_squared_plus"], nameUnicode: "SQUARED PLUS", width: "+0.5ex" },
    { symbol: "⊟", unicodeHex: "229F", code: 8863, alias: "squared_minus", name: "squared_minus", tags: ["color_squared_minus"], nameUnicode: "SQUARED MINUS", width: "+0.5ex" },
    { symbol: "⊠", unicodeHex: "22A0", code: 8864, alias: "squared_times", name: "squared_times", tags: ["color_squared_times"], nameUnicode: "SQUARED TIMES", width: "+0.5ex" },
    { symbol: "⊡", unicodeHex: "22A1", code: 8865, alias: "squared_dot", name: "squared_dot_operator", tags: ["color_squared_dot"], nameUnicode: "SQUARED DOT OPERATOR", width: "+0.5ex" },
    { symbol: "⛝", unicodeHex: "26DD", code: 9949, alias: "squared_saltire", name: "squared_saltire", tags: ["color_squared_saltire"], nameUnicode: "SQUARED SALTIRE", width: "+0.5ex" },
    { symbol: "⧇", unicodeHex: "29C7", code: 10695, alias: "squared_circle", name: "squared_small_circle", tags: ["color_squared_circle"], nameUnicode: "SQUARED SMALL CIRCLE", width: "+0.5ex" },
    { symbol: "⧈", unicodeHex: "29C8", code: 10696, alias: "squared_square", name: "squared_square", tags: ["color_squared_square"], nameUnicode: "SQUARED SQUARE", width: "+0.5ex" },
    { symbol: "⧆", unicodeHex: "29C6", code: 10694, alias: "squared_asterisk", name: "squared_asterisk", tags: ["color_squared_asterisk"], nameUnicode: "SQUARED ASTERISK", width: "+0.5ex" },
    { symbol: "⧄", unicodeHex: "29C4", code: 10692, alias: "squared_slash", name: "squared_rising_diagonal_slash", tags: ["color_squared_slash"], nameUnicode: "SQUARED RISING DIAGONAL SLASH", width: "+0.5ex" },
    { symbol: "⃠", unicodeHex: "20E0", code: 8416, alias: "circle_backslash", name: "combining_enclosing_circle_backslash", tags: ["color_circle_backslash"], nameUnicode: "COMBINING ENCLOSING CIRCLE BACKSLASH", width: "+0.5ex" },
    { symbol: "⊕", unicodeHex: "2295", code: 8853, alias: "circled_plus", name: "circled_plus", tags: ["color_circled_plus"], nameUnicode: "CIRCLED PLUS", width: "+0.5ex" },
    { symbol: "⊖", unicodeHex: "2296", code: 8854, alias: "circled_minus", name: "circled_minus", tags: ["color_circled_minus"], nameUnicode: "CIRCLED MINUS", width: "+0.5ex" },
    { symbol: "⊗", unicodeHex: "2297", code: 8855, alias: "circled_times", name: "circled_times", tags: ["color_circled_times"], nameUnicode: "CIRCLED TIMES", width: "+0.5ex" },
    { symbol: "⊘", unicodeHex: "2298", code: 8856, alias: "circled_division", name: "circled_division_slash", tags: ["color_circled_division"], nameUnicode: "CIRCLED DIVISION SLASH", width: "+0.5ex" },
    { symbol: "⊙", unicodeHex: "2299", code: 8857, alias: "circled_dot", name: "circled_dot_operator", tags: ["color_circled_dot"], nameUnicode: "CIRCLED DOT OPERATOR", width: "+0.5ex" },
    { symbol: "⊚", unicodeHex: "229A", code: 8858, alias: "circled_ring", name: "circled_ring_operator", tags: ["color_circled_ring"], nameUnicode: "CIRCLED RING OPERATOR", width: "+0.5ex" },
    { symbol: "⊛", unicodeHex: "229B", code: 8859, alias: "circled_asterisk", name: "circled_asterisk_operator", tags: ["color_circled_asterisk"], nameUnicode: "CIRCLED ASTERISK OPERATOR", width: "+0.5ex" },
    { symbol: "⊜", unicodeHex: "229C", code: 8860, alias: "circled_equals", name: "circled_equals", tags: ["color_circled_equals"], nameUnicode: "CIRCLED EQUALS", width: "+0.5ex" },
    { symbol: "⊝", unicodeHex: "229D", code: 8861, alias: "circled_dash", name: "circled_dash", tags: ["color_circled_dash"], nameUnicode: "CIRCLED DASH", width: "+0.5ex" },
    { symbol: "⎊", unicodeHex: "238A", code: 9098, alias: "circled_triangle_down", name: "circled_triangle_down", tags: ["color_circled_triangle_down"], nameUnicode: "CIRCLED TRIANGLE DOWN", width: "+0.5ex" },
    { symbol: "⏣", unicodeHex: "23E3", code: 9187, alias: "benzene_ring", name: "benzene_ring_with_circle", tags: ["color_benzene_ring"], nameUnicode: "BENZENE RING WITH CIRCLE", width: "+0.5ex" },
    { symbol: "✓", unicodeHex: "2713", code: 10003, alias: "check_mark", name: "check_mark", tags: ["color_check_mark"], nameUnicode: "CHECK MARK", width: "+0.5ex" },
    { symbol: "‘", unicodeHex: "2018", code: 8216, alias: "single_quote_left", name: "left_single_quotation_mark", tags: ["color_single_quote_left"], nameUnicode: "LEFT SINGLE QUOTATION MARK", width: "+0.3ex" },
    { symbol: "’", unicodeHex: "2019", code: 8217, alias: "single_quote_right", name: "right_single_quotation_mark", tags: ["color_single_quote_right"], nameUnicode: "RIGHT SINGLE QUOTATION MARK", width: "+0.3ex" },
    { symbol: "‚", unicodeHex: "201A", code: 8218, alias: "single_quote_low", name: "single_low_9_quotation_mark", tags: ["color_single_quote_low"], nameUnicode: "SINGLE LOW-9 QUOTATION MARK", width: "+0.3ex" },
    { symbol: "‛", unicodeHex: "201B", code: 8219, alias: "single_quote_reversed", name: "single_high_reversed_9_quotation_mark", tags: ["color_single_quote_reversed"], nameUnicode: "SINGLE HIGH-REVERSED-9 QUOTATION MARK", width: "+0.3ex" },
    { symbol: "“", unicodeHex: "201C", code: 8220, alias: "double_quote_left", name: "left_double_quotation_mark", tags: ["color_double_quote_left"], nameUnicode: "LEFT DOUBLE QUOTATION MARK", width: "+0.3ex" },
    { symbol: "”", unicodeHex: "201D", code: 8221, alias: "double_quote_right", name: "right_double_quotation_mark", tags: ["color_double_quote_right"], nameUnicode: "RIGHT DOUBLE QUOTATION MARK", width: "+0.3ex" },
    { symbol: "„", unicodeHex: "201E", code: 8222, alias: "double_quote_low", name: "double_low_9_quotation_mark", tags: ["color_double_quote_low"], nameUnicode: "DOUBLE LOW-9 QUOTATION MARK", width: "+0.3ex" },
    { symbol: "❛", unicodeHex: "275B", code: 10075, alias: "heavy_single_quote_turned", name: "heavy_single_turned_comma_quotation_mark_ornament", tags: ["color_heavy_single_quote_turned"], nameUnicode: "HEAVY SINGLE TURNED COMMA QUOTATION MARK ORNAMENT", width: "+0.3ex" },
    { symbol: "❜", unicodeHex: "275C", code: 10076, alias: "heavy_single_quote", name: "heavy_single_comma_quotation_mark_ornament", tags: ["color_heavy_single_quote"], nameUnicode: "HEAVY SINGLE COMMA QUOTATION MARK ORNAMENT", width: "+0.3ex" },
    { symbol: "❝", unicodeHex: "275D", code: 10077, alias: "heavy_double_quote_turned", name: "heavy_double_turned_comma_quotation_mark_ornament", tags: ["color_heavy_double_quote_turned"], nameUnicode: "HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT", width: "+0.3ex" },
    { symbol: "❞", unicodeHex: "275E", code: 10078, alias: "heavy_double_quote", name: "heavy_double_comma_quotation_mark_ornament", tags: ["color_heavy_double_quote"], nameUnicode: "HEAVY DOUBLE COMMA QUOTATION MARK ORNAMENT", width: "+0.3ex" },
    { symbol: "Ⓐ", unicodeHex: "24B6", code: 9398, alias: "circled_capital_a", name: "circled_latin_capital_a", tags: ["color_circled_capital_a"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER A", width: "+0.6ex" },
    { symbol: "Ⓑ", unicodeHex: "24B7", code: 9399, alias: "circled_capital_b", name: "circled_latin_capital_b", tags: ["color_circled_capital_b"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER B", width: "+0.6ex" },
    { symbol: "Ⓒ", unicodeHex: "24B8", code: 9400, alias: "circled_capital_c", name: "circled_latin_capital_c", tags: ["color_circled_capital_c"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER C", width: "+0.6ex" },
    { symbol: "Ⓓ", unicodeHex: "24B9", code: 9401, alias: "circled_capital_d", name: "circled_latin_capital_d", tags: ["color_circled_capital_d"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER D", width: "+0.6ex" },
    { symbol: "Ⓔ", unicodeHex: "24BA", code: 9402, alias: "circled_capital_e", name: "circled_latin_capital_e", tags: ["color_circled_capital_e"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER E", width: "+0.6ex" },
    { symbol: "Ⓕ", unicodeHex: "24BB", code: 9403, alias: "circled_capital_f", name: "circled_latin_capital_f", tags: ["color_circled_capital_f"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER F", width: "+0.6ex" },
    { symbol: "Ⓖ", unicodeHex: "24BC", code: 9404, alias: "circled_capital_g", name: "circled_latin_capital_g", tags: ["color_circled_capital_g"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER G", width: "+0.6ex" },
    { symbol: "Ⓗ", unicodeHex: "24BD", code: 9405, alias: "circled_capital_h", name: "circled_latin_capital_h", tags: ["color_circled_capital_h"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER H", width: "+0.6ex" },
    { symbol: "Ⓘ", unicodeHex: "24BE", code: 9406, alias: "circled_capital_i", name: "circled_latin_capital_i", tags: ["color_circled_capital_i"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER I", width: "+0.6ex" },
    { symbol: "Ⓙ", unicodeHex: "24BF", code: 9407, alias: "circled_capital_j", name: "circled_latin_capital_j", tags: ["color_circled_capital_j"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER J", width: "+0.6ex" },
    { symbol: "Ⓚ", unicodeHex: "24C0", code: 9408, alias: "circled_capital_k", name: "circled_latin_capital_k", tags: ["color_circled_capital_k"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER K", width: "+0.6ex" },
    { symbol: "Ⓛ", unicodeHex: "24C1", code: 9409, alias: "circled_capital_l", name: "circled_latin_capital_l", tags: ["color_circled_capital_l"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER L", width: "+0.6ex" },
    { symbol: "Ⓜ", unicodeHex: "24C2", code: 9410, alias: "circled_capital_m", name: "circled_latin_capital_m", tags: ["color_circled_capital_m"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER M", width: "+0.6ex" },
    { symbol: "Ⓝ", unicodeHex: "24C3", code: 9411, alias: "circled_capital_n", name: "circled_latin_capital_n", tags: ["color_circled_capital_n"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER N", width: "+0.6ex" },
    { symbol: "Ⓞ", unicodeHex: "24C4", code: 9412, alias: "circled_capital_o", name: "circled_latin_capital_o", tags: ["color_circled_capital_o"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER O", width: "+0.6ex" },
    { symbol: "Ⓟ", unicodeHex: "24C5", code: 9413, alias: "circled_capital_p", name: "circled_latin_capital_p", tags: ["color_circled_capital_p"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER P", width: "+0.6ex" },
    { symbol: "Ⓠ", unicodeHex: "24C6", code: 9414, alias: "circled_capital_q", name: "circled_latin_capital_q", tags: ["color_circled_capital_q"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER Q", width: "+0.6ex" },
    { symbol: "Ⓡ", unicodeHex: "24C7", code: 9415, alias: "circled_capital_r", name: "circled_latin_capital_r", tags: ["color_circled_capital_r"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER R", width: "+0.6ex" },
    { symbol: "Ⓢ", unicodeHex: "24C8", code: 9416, alias: "circled_capital_s", name: "circled_latin_capital_s", tags: ["color_circled_capital_s"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER S", width: "+0.6ex" },
    { symbol: "Ⓣ", unicodeHex: "24C9", code: 9417, alias: "circled_capital_t", name: "circled_latin_capital_t", tags: ["color_circled_capital_t"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER T", width: "+0.6ex" },
    { symbol: "Ⓤ", unicodeHex: "24CA", code: 9418, alias: "circled_capital_u", name: "circled_latin_capital_u", tags: ["color_circled_capital_u"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER U", width: "+0.6ex" },
    { symbol: "Ⓥ", unicodeHex: "24CB", code: 9419, alias: "circled_capital_v", name: "circled_latin_capital_v", tags: ["color_circled_capital_v"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER V", width: "+0.6ex" },
    { symbol: "Ⓦ", unicodeHex: "24CC", code: 9420, alias: "circled_capital_w", name: "circled_latin_capital_w", tags: ["color_circled_capital_w"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER W", width: "+0.6ex" },
    { symbol: "Ⓧ", unicodeHex: "24CD", code: 9421, alias: "circled_capital_x", name: "circled_latin_capital_x", tags: ["color_circled_capital_x"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER X", width: "+0.6ex" },
    { symbol: "Ⓨ", unicodeHex: "24CE", code: 9422, alias: "circled_capital_y", name: "circled_latin_capital_y", tags: ["color_circled_capital_y"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER Y", width: "+0.6ex" },
    { symbol: "Ⓩ", unicodeHex: "24CF", code: 9423, alias: "circled_capital_z", name: "circled_latin_capital_z", tags: ["color_circled_capital_z"], nameUnicode: "CIRCLED LATIN CAPITAL LETTER Z", width: "+0.6ex" },
    { symbol: "ⓐ", unicodeHex: "24D0", code: 9424, alias: "circled_a", name: "circled_latin_small_a", tags: ["color_circled_a"], nameUnicode: "CIRCLED LATIN SMALL LETTER A", width: "+0.6ex" },
    { symbol: "ⓑ", unicodeHex: "24D1", code: 9425, alias: "circled_b", name: "circled_latin_small_b", tags: ["color_circled_b"], nameUnicode: "CIRCLED LATIN SMALL LETTER B", width: "+0.6ex" },
    { symbol: "ⓒ", unicodeHex: "24D2", code: 9426, alias: "circled_c", name: "circled_latin_small_c", tags: ["color_circled_c"], nameUnicode: "CIRCLED LATIN SMALL LETTER C", width: "+0.6ex" },
    { symbol: "ⓓ", unicodeHex: "24D3", code: 9427, alias: "circled_d", name: "circled_latin_small_d", tags: ["color_circled_d"], nameUnicode: "CIRCLED LATIN SMALL LETTER D", width: "+0.6ex" },
    { symbol: "ⓔ", unicodeHex: "24D4", code: 9428, alias: "circled_e", name: "circled_latin_small_e", tags: ["color_circled_e"], nameUnicode: "CIRCLED LATIN SMALL LETTER E", width: "+0.6ex" },
    { symbol: "ⓕ", unicodeHex: "24D5", code: 9429, alias: "circled_f", name: "circled_latin_small_f", tags: ["color_circled_f"], nameUnicode: "CIRCLED LATIN SMALL LETTER F", width: "+0.6ex" },
    { symbol: "ⓖ", unicodeHex: "24D6", code: 9430, alias: "circled_g", name: "circled_latin_small_g", tags: ["color_circled_g"], nameUnicode: "CIRCLED LATIN SMALL LETTER G", width: "+0.6ex" },
    { symbol: "ⓗ", unicodeHex: "24D7", code: 9431, alias: "circled_h", name: "circled_latin_small_h", tags: ["color_circled_h"], nameUnicode: "CIRCLED LATIN SMALL LETTER H", width: "+0.6ex" },
    { symbol: "ⓘ", unicodeHex: "24D8", code: 9432, alias: "circled_i", name: "circled_latin_small_i", tags: ["color_circled_i"], nameUnicode: "CIRCLED LATIN SMALL LETTER I", width: "+0.6ex" },
    { symbol: "ⓙ", unicodeHex: "24D9", code: 9433, alias: "circled_j", name: "circled_latin_small_j", tags: ["color_circled_j"], nameUnicode: "CIRCLED LATIN SMALL LETTER J", width: "+0.6ex" },
    { symbol: "ⓚ", unicodeHex: "24DA", code: 9434, alias: "circled_k", name: "circled_latin_small_k", tags: ["color_circled_k"], nameUnicode: "CIRCLED LATIN SMALL LETTER K", width: "+0.6ex" },
    { symbol: "ⓛ", unicodeHex: "24DB", code: 9435, alias: "circled_l", name: "circled_latin_small_l", tags: ["color_circled_l"], nameUnicode: "CIRCLED LATIN SMALL LETTER L", width: "+0.6ex" },
    { symbol: "ⓜ", unicodeHex: "24DC", code: 9436, alias: "circled_m", name: "circled_latin_small_m", tags: ["color_circled_m"], nameUnicode: "CIRCLED LATIN SMALL LETTER M", width: "+0.6ex" },
    { symbol: "ⓝ", unicodeHex: "24DD", code: 9437, alias: "circled_n", name: "circled_latin_small_n", tags: ["color_circled_n"], nameUnicode: "CIRCLED LATIN SMALL LETTER N", width: "+0.6ex" },
    { symbol: "ⓞ", unicodeHex: "24DE", code: 9438, alias: "circled_o", name: "circled_latin_small_o", tags: ["color_circled_o"], nameUnicode: "CIRCLED LATIN SMALL LETTER O", width: "+0.6ex" },
    { symbol: "ⓟ", unicodeHex: "24DF", code: 9439, alias: "circled_p", name: "circled_latin_small_p", tags: ["color_circled_p"], nameUnicode: "CIRCLED LATIN SMALL LETTER P", width: "+0.6ex" },
    { symbol: "ⓠ", unicodeHex: "24E0", code: 9440, alias: "circled_q", name: "circled_latin_small_q", tags: ["color_circled_q"], nameUnicode: "CIRCLED LATIN SMALL LETTER Q", width: "+0.6ex" },
    { symbol: "ⓡ", unicodeHex: "24E1", code: 9441, alias: "circled_r", name: "circled_latin_small_r", tags: ["color_circled_r"], nameUnicode: "CIRCLED LATIN SMALL LETTER R", width: "+0.6ex" },
    { symbol: "ⓢ", unicodeHex: "24E2", code: 9442, alias: "circled_s", name: "circled_latin_small_s", tags: ["color_circled_s"], nameUnicode: "CIRCLED LATIN SMALL LETTER S", width: "+0.6ex" },
    { symbol: "ⓣ", unicodeHex: "24E3", code: 9443, alias: "circled_t", name: "circled_latin_small_t", tags: ["color_circled_t"], nameUnicode: "CIRCLED LATIN SMALL LETTER T", width: "+0.6ex" },
    { symbol: "ⓤ", unicodeHex: "24E4", code: 9444, alias: "circled_u", name: "circled_latin_small_u", tags: ["color_circled_u"], nameUnicode: "CIRCLED LATIN SMALL LETTER U", width: "+0.6ex" },
    { symbol: "ⓥ", unicodeHex: "24E5", code: 9445, alias: "circled_v", name: "circled_latin_small_v", tags: ["color_circled_v"], nameUnicode: "CIRCLED LATIN SMALL LETTER V", width: "+0.6ex" },
    { symbol: "ⓦ", unicodeHex: "24E6", code: 9446, alias: "circled_w", name: "circled_latin_small_w", tags: ["color_circled_w"], nameUnicode: "CIRCLED LATIN SMALL LETTER W", width: "+0.6ex" },
    { symbol: "ⓧ", unicodeHex: "24E7", code: 9447, alias: "circled_x", name: "circled_latin_small_x", tags: ["color_circled_x"], nameUnicode: "CIRCLED LATIN SMALL LETTER X", width: "+0.6ex" },
    { symbol: "ⓨ", unicodeHex: "24E8", code: 9448, alias: "circled_y", name: "circled_latin_small_y", tags: ["color_circled_y"], nameUnicode: "CIRCLED LATIN SMALL LETTER Y", width: "+0.6ex" },
    { symbol: "ⓩ", unicodeHex: "24E9", code: 9449, alias: "circled_z", name: "circled_latin_small_z", tags: ["color_circled_z"], nameUnicode: "CIRCLED LATIN SMALL LETTER Z", width: "+0.6ex" },
    { symbol: "⍰", unicodeHex: "2370", code: 9072, alias: "squared_question", name: "apl_functional_symbol_quad_question", tags: ["color_squared_question"], nameUnicode: "APL FUNCTIONAL SYMBOL QUAD QUESTION", width: "+0.6ex" },
    { symbol: "⌦", unicodeHex: "2326", code: 8998, alias: "erase_right", name: "erase_to_the_right", tags: ["color_erase_right"], nameUnicode: "ERASE TO THE RIGHT", width: "+0.6ex" },
    { symbol: "⌫", unicodeHex: "232B", code: 9003, alias: "erase_left", name: "erase_to_the_left", tags: ["color_erase_left"], nameUnicode: "ERASE TO THE LEFT", width: "+0.6ex" },
    { "symbol": "✆", "unicodeHex": "2706", "code": 9990, "alias": "telephone_location", "name": "telephone_location_sign", "tags": ["color_telephone_location"], "nameUnicode": "TELEPHONE LOCATION SIGN", "width": "+0.6ex" },
];
//# sourceMappingURL=unicode-icons.js.map