"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.tabularStyles = void 0;
var colors_1 = require("./colors");
var tabularStyles = function (useColors, isPptx) {
    if (useColors === void 0) { useColors = true; }
    if (isPptx === void 0) { isPptx = false; }
    var cellColors = useColors && !isPptx;
    return "\n    .table_tabular,\n    #preview-content .table_tabular, #setText .table_tabular {\n        overflow-x: auto;\n        padding: 0 2px 0.5em 2px;\n    }\n    .tabular,\n    #preview-content .tabular, #setText .tabular {\n        display: inline-table !important;\n        width: auto;\n        table-layout: auto;\n        border-collapse: collapse;\n        border-spacing: 0;\n        margin: 0 0 1em;\n        font-size: inherit;\n        height: fit-content;\n    }\n    .tabular th,\n    #preview-content .tabular th, #setText .tabular th {\n        border: none !important;\n        padding: 6px 13px;\n        background-color: transparent;\n        font-weight: bold;\n    }\n    .tabular tr,\n    #preview-content .tabular tr, #setText .tabular tr {\n        border-top: none !important;\n        border-bottom: none !important;\n        background-color: transparent;\n    }\n    .tabular td,\n    #preview-content .tabular td, #setText .tabular td {\n        border-style: none !important;\n        ".concat(cellColors ? "background-color: ".concat(colors_1.COLOR_TABULAR_TD_BG, ";") : 'background-color: transparent;', "\n        ").concat(cellColors ? "border-color: ".concat(colors_1.COLOR_TABULAR_TD_BORDER, " !important;") : 'border-color: currentColor !important;', "\n        word-break: keep-all;\n        padding: 0.1em 0.5em !important;\n    }\n    .tabular td > p,\n    #preview-content .tabular td > p, #setText .tabular td > p {\n        margin-bottom: 0;\n        margin-top: 0;\n    }\n    .tabular td._empty,\n    #preview-content .tabular td._empty, #setText .tabular td._empty {\n        height: 1.3em;\n    }\n    .tabular td .f,\n    #preview-content .tabular td .f, #setText .tabular td .f {\n        opacity: 0;\n    }\n    #preview-content .sub-table table, #setText .sub-table table {\n        margin-bottom: 0;\n    }\n    html[data-theme=\"dark\"] .tabular tr,\n    html[data-theme=\"dark\"] #preview-content .tabular tr, html[data-theme=\"dark\"] #setText .tabular tr,\n    html[data-theme=\"dark\"] .tabular td,\n    html[data-theme=\"dark\"] #preview-content .tabular td, html[data-theme=\"dark\"] #setText .tabular td {\n        ").concat(cellColors ? "background-color: ".concat(colors_1.COLOR_DARK_BG, ";") : 'background-color: transparent;', "\n        ").concat(cellColors ? "border-color: ".concat(colors_1.COLOR_DARK_TABULAR_TD_BORDER, " !important;") : 'border-color: currentColor !important;', "\n    }\n    .figure_img,\n    #preview-content .figure_img, #setText .figure_img {\n        margin-bottom: 0.5em;\n        overflow-x: auto;\n    }\n    div.figure_img img,\n    #preview-content div.figure_img img, #setText div.figure_img img {\n        ").concat(!isPptx ? 'display: inline;' : '', "\n        margin: 0;\n    }\n");
};
exports.tabularStyles = tabularStyles;
//# sourceMappingURL=styles-tabular.js.map