declare const namespaces: {
    a: string;
    b: string;
    cdr: string;
    dc: string;
    dcmitype: string;
    dcterms: string;
    o: string;
    pic: string;
    r: string;
    v: string;
    ve: string;
    vt: string;
    w: string;
    w10: string;
    wp: string;
    wne: string;
    xsd: string;
    xsi: string;
    numbering: string;
    hyperlinks: string;
    images: string;
    styles: string;
    headers: string;
    coreProperties: string;
    officeDocumentRelation: string;
    corePropertiesRelation: string;
    settingsRelation: string;
    webSettingsRelation: string;
    sl: string;
};
export default namespaces;
