export declare const defaultHeadingSizesInPixel: {
    h1: number;
    h2: number;
    h3: number;
    h4: number;
    h5: number;
    h6: number;
};
export declare const pixelRegex: RegExp;
export declare const percentageRegex: RegExp;
export declare const pointRegex: RegExp;
export declare const cmRegex: RegExp;
export declare const inchRegex: RegExp;
export declare const pixelToEMU: (pixelValue: any) => number;
export declare const EMUToPixel: (EMUValue: any) => number;
export declare const TWIPToEMU: (TWIPValue: any) => number;
export declare const EMUToTWIP: (EMUValue: any) => number;
export declare const pointToTWIP: (pointValue: any) => number;
export declare const TWIPToPoint: (TWIPValue: any) => number;
export declare const pointToHIP: (pointValue: any) => number;
export declare const HIPToPoint: (HIPValue: any) => number;
export declare const HIPToTWIP: (HIPValue: any) => number;
export declare const TWIPToHIP: (TWIPValue: any) => number;
export declare const pixelToTWIP: (pixelValue: any) => number;
export declare const TWIPToPixel: (TWIPValue: any) => number;
export declare const pixelToHIP: (pixelValue: any) => number;
export declare const HIPToPixel: (HIPValue: any) => number;
export declare const inchToPoint: (inchValue: any) => number;
export declare const inchToTWIP: (inchValue: any) => number;
export declare const cmToInch: (cmValue: any) => number;
export declare const cmToTWIP: (cmValue: any) => number;
export declare const pixelToPoint: (pixelValue: any) => number;
export declare const pointToPixel: (pointValue: any) => number;
export declare const EIPToPoint: (EIPValue: any) => number;
export declare const pointToEIP: (PointValue: any) => number;
export declare const pixelToEIP: (pixelValue: any) => number;
export declare const EIPToPixel: (EIPValue: any) => number;
