import { HandlerFn } from "./types";
export declare const mfrac: HandlerFn;
export declare const msup: HandlerFn;
export declare const msub: HandlerFn;
export declare const msubsup: HandlerFn;
export declare const msqrt: HandlerFn;
export declare const mroot: HandlerFn;
export declare const mover: HandlerFn;
export declare const munder: HandlerFn;
export declare const munderover: HandlerFn;
export declare const mmultiscripts: HandlerFn;
