export declare const attr_value: string;
export declare const attribute: string;
export declare const openTagMML: RegExp;
export declare const closeTagMML: RegExp;
export declare const open_tag_smiles: string;
export declare const reOpenTagSmiles: RegExp;
export declare const reSpan: RegExp;
export declare const closeTagSpan: RegExp;
export declare const labelTag: RegExp;
export declare const labelTagG: RegExp;
export declare const openTag: RegExp;
export declare const openTagDescription: RegExp;
export declare const openTagProof: RegExp;
export declare const reNewTheoremG: RegExp;
export declare const reNewTheoremInit: RegExp;
export declare const reNewTheoremUnNumberedInit: RegExp;
export declare const reNewTheorem: RegExp;
export declare const reNewTheoremNumbered: RegExp;
export declare const reNewTheoremNumbered2: RegExp;
export declare const reNewTheoremUnNumbered: RegExp;
export declare const reTheoremStyle: RegExp;
export declare const reTheoremStyleG: RegExp;
export declare const defTheoremStyle = "plain";
export declare const reNewCommandQedSymbol: RegExp;
export declare const reNewCommandQedSymbolG: RegExp;
export declare const defQED = "$\\square$";
export declare const reSetCounter: RegExp;
export declare const reSetCounterG: RegExp;
export declare const reAddContentsLine: RegExp;
export declare const reAddContentsLineG: RegExp;
export declare const latexEnvironments: string[];
/** https://docs.mathjax.org/en/v3.0-latest/input/tex/macros/index.html#environments */
export declare const mathEnvironments: string[];
export declare const tsvSeparatorsDef: {
    column: string;
    row: string;
};
